# Generated by Django 5.0.2 on 2024-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_vlog_record_vlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='vlog',
        ),
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(default=34, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='vlog_image',
            field=models.ImageField(default=0, upload_to='vlogs/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vlog',
        ),
    ]
